# Generated by Django 3.1.3 on 2020-11-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=80)),
                ('phone_number', models.CharField(max_length=11)),
                ('birthday', models.DateField()),
                ('is_critic', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('blocked_status', models.BooleanField()),
                ('blocked_at', models.DateTimeField(auto_now=True)),
                ('activate_status', models.BooleanField()),
                ('deactivated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
