# Generated by Django 3.1.3 on 2020-11-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='deactivated_at',
            new_name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='activate_status',
        ),
        migrations.AddField(
            model_name='user',
            name='delete_status',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='user',
            name='blocked_status',
            field=models.BooleanField(default=False, verbose_name='Blocked'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_critic',
            field=models.BooleanField(default=False, verbose_name='Critic'),
        ),
    ]
